
/**
 *	interface for Matchers generated by 
 *	the matcherfactory
 *
 */
public interface Matcher
{
	/**
	 *	match given string to the matching rule represented by this
	 *	matcher
	 *	@param s - string to match
	 * 	@return true if matched ,false if not
	 */
	public boolean match(String s);
	
	/**
	 *	match given part of a string 
	 *	@param s - string to match
	 *	@param off - offset to string
	 *	@param len - length to match
	 */
	public boolean match(String s,int off,int len);
}
